<?php
/**
 * Projet : nessi
 * Auteur : Raphaël Gabriel
 * Date: 10.02.2017
 */

namespace App\Controller\Admin;


use App\Controller\AppController;

class AdminAppController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}