-- MySQL Script generated by MySQL Workbench
-- 02/09/17 10:43:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nessi_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nessi_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nessi_dev` DEFAULT CHARACTER SET utf8 ;
USE `nessi_dev` ;

-- -----------------------------------------------------
-- Table `nessi_dev`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `group_id` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `lft` INT NOT NULL,
  `rght` INT NOT NULL,
  PRIMARY KEY (`id`, `group_id`),
  INDEX `fk_users_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `nessi_dev`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`branches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`marks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  `coefficient` FLOAT NOT NULL,
  `exam_date` DATETIME NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `branch_id`),
  INDEX `fk_marks_branches1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_marks_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `nessi_dev`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`academicyears`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`academicyears` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`establishments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`establishments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `academicyear_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `gmapid` VARCHAR(255) NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `academicyear_id`),
  INDEX `fk_establishments_academicyears1_idx` (`academicyear_id` ASC),
  CONSTRAINT `fk_establishments_academicyears1`
    FOREIGN KEY (`academicyear_id`)
    REFERENCES `nessi_dev`.`academicyears` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`school_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`school_classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `establishment_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `establishment_id`),
  INDEX `fk_grades_establishments1_idx` (`establishment_id` ASC),
  CONSTRAINT `fk_grades_establishments1`
    FOREIGN KEY (`establishment_id`)
    REFERENCES `nessi_dev`.`establishments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`branches_school_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`branches_school_classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `school_class_id` INT NOT NULL,
  `avg_round` VARCHAR(45) NULL,
  `avg_semester` VARCHAR(255) NULL,
  `avg_sup` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`, `branch_id`, `school_class_id`),
  INDEX `fk_branches_grades_branches_idx` (`branch_id` ASC),
  INDEX `fk_branches_grades_grades1_idx` (`school_class_id` ASC),
  CONSTRAINT `fk_branches_grades_branches`
    FOREIGN KEY (`branch_id`)
    REFERENCES `nessi_dev`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branches_grades_grades1`
    FOREIGN KEY (`school_class_id`)
    REFERENCES `nessi_dev`.`school_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`school_classes_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`school_classes_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_class_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `school_class_id`, `user_id`),
  INDEX `fk_grades_users_grades1_idx` (`school_class_id` ASC),
  INDEX `fk_grades_users_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_grades_users_grades1`
    FOREIGN KEY (`school_class_id`)
    REFERENCES `nessi_dev`.`school_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `nessi_dev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nessi_dev`.`terms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nessi_dev`.`terms` (
  `id` INT NOT NULL,
  `academicyear_id` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `created` DATETIME NOT NULL,
  `modifed` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `academicyear_id`),
  INDEX `fk_terms_academicyears1_idx` (`academicyear_id` ASC),
  CONSTRAINT `fk_terms_academicyears1`
    FOREIGN KEY (`academicyear_id`)
    REFERENCES `nessi_dev`.`academicyears` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
